### ISSUE TITLE
Why are you Disabling Issues?

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC-Dev/UnraveledMCMod#1]
I've noticed that whenever I enable issues, the next day they're disabled.
I had made like 6 issues regarding some critical bugs and they're all gone now?

**Comment by OutOfYourMind** [comment]
I deleted the repo's and made new ones because when I made them, NetBean errors were everywhere.

**Comment by aggelosQQ** [comment]
oh lol
