### ISSUE TITLE
CoreProtect Dependency

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC-Dev/UnraveledMCMod#10]
Since /rb rollbacks using CoreProtect, (ce66e25) shouldn't CoreProtect be a dependency?

@OxLemonxO

**Comment by CreeperSeth** [comment]
I'll add it

**Comment by CreeperSeth** [comment]
CoreProtect has been added as a dependancy

**Comment by OxLemonxO** [comment]
It doesnt need CoreProtect as a dependency.... CreeperSeth didnt want CoreProtect as  a dependency so I used server.dispatchCommand.

**Comment by CreeperSeth** [comment]
Oh, right.

**Comment by CreeperSeth** [comment]
Alright it has been removed as a dependancy, thanks @OxLemonxO
