### ISSUE TITLE
Block some tool commands.

### ISSUE THREAD

**Issue by SixtyFourWarrior** [UnraveledMC-Dev/UnraveledMCMod#11]
You should block these commands from config:
/tool (because it includes /tool lrbuild /tool floodfill etc.).
/cycler (changes block datas, easy to grief stained glass, stained clay, wool etc. builds with it.)
/repl (changes blocks to a specified block, easy to grief every build with it.)
/farwand [not sure about this] (like //wand , but can select pos1 and pos2 from anywhere.)

**Comment by CreeperSeth** [comment]
/repl is useful, /tool to me is pointless so I will block it, /cycler never really was a problem here or on Total Freedom, /farwand never see anyone using it. Thanks for the suggestion!

**Comment by CreeperSeth** [comment]
Added /tool to the admin only section in the config
