### ISSUE TITLE
Add Bold and Italics

### ISSUE THREAD

**Issue by OutOfYourMind** [UnraveledMC-Dev/UnraveledMCMod#14]
@CreeperSeth and/or @OxLemonxO can you add Bold and Italics to the shop both as individual items for 20 coins each?

**Comment by aggelosQQ** [comment]
And as sub-items for the ColoredChat (like 2nd gui when you press the already-purchased item).

**Comment by CreeperSeth** [comment]
This is going to take a long time for me to add each color for each item, it is stupid as hell and it makes no sense and I find it a lot more convienent to just use the & color code. I say we ask what our players want, we make a poll on the forum asking if they want items for the colored chat, or & color codes. I don't want to loose sanity adding items for 20 different colors unless the players really want it.

**Comment by aggelosQQ** [comment]
No, the way it works will still be the same. They won't be purchasing the colors but the effects of the colors and they are just two, bold and italic.

**Comment by DUFCLiam** [comment]
I could try and implement this if accepted.

**Comment by aggelosQQ** [comment]
@DUFCLiam if you can, go ahead.
