### ISSUE TITLE
Plugin Update

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC-Dev/UnraveledMCMod#2]
TotalFreedomMod has recently been updated.

Resp: https://github.com/totalfreedom/totalfreedommod

Latest Release: https://github.com/TotalFreedom/TotalFreedomMod/releases/tag/v5.0

@UnraveledMC-Dev/developers

**Comment by CreeperSeth** [comment]
I'll start migrating changes

**Comment by CreeperSeth** [comment]
Ivan forked the project after the latest release as you can see the changes labeled TotalFreedom Electrum

**Comment by CreeperSeth** [comment]
Never mind, I see they have a new branch

**Comment by CreeperSeth** [comment]
I have synced everything from the tfm51 branch. We are good for now
