### ISSUE TITLE
Actionbar & BossBar purchaseable permission (New Items)

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC-Dev/UnraveledMCMod#23]
New /shop item which will give permission to the user to use actionbar or bossbar (different items)

Estimated price: 75 on both (individual items).

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by CreeperSeth** [comment]
I've just noticed someone trying to advertise using with the command, I don't think we should do this and just make the command admin only.

**Comment by aggelosQQ** [comment]
Well, if they use it to break the rules, we will ban them and reset their coins, as well as thank them for voting.
