### ISSUE TITLE
How is doing /wildcard stop rogue activity

### ISSUE THREAD

**Issue by OxLemonxO** [UnraveledMC-Dev/UnraveledMCMod#4]
??
It does the exact same thing as /stop, but spams.
After the server comes back up, it wont stop again lol
So why do we need to block it?

**Comment by CreeperSeth** [comment]
Because only an enraged admin would do /wildcard stop

**Comment by OxLemonxO** [comment]
it's no different from /stop lol
\

**Comment by CreeperSeth** [comment]
Lets just say it's because of Chuck Norris

**Comment by aggelosQQ** [comment]
@OxLemonxO since this command is a forbidden one, it would ban every non-admin.

**Comment by OxLemonxO** [comment]
@aggelosQQ that's only with /wildcard gcmd ? stop
/wildcard doesn't make other players do commands.

**Comment by CreeperSeth** [comment]
If you want I can count /wildcard gcmd as rouge activity

**Comment by OxLemonxO** [comment]
wildcard gcmd is helpful, you can do /ai and etc with it

**Comment by aggelosQQ** [comment]
Oh true, he could block this exact syntax ```/wildcard gcmd ? stop````

**Comment by CreeperSeth** [comment]
Why would you wildcard gcmd someone to do /ai

**Comment by ThePheonixBlader** [comment]
Because if someone asks how to apply for admin, that's what we're supposed to do? /gcmd <player> ai
Or if multiple people ask, /wildcard gcmd ? ai
Easy answer.

**Comment by aggelosQQ** [comment]
@CreeperSeth that's actually common.

**Comment by CreeperSeth** [comment]
I will have more ways of stopping rouge inactivity in the future. This is just the beginning, trust me on this.
